CC = gcc
CFLAGS =
LIB =

all:main_sidharth

hello:
	$(CC) $(CFLAGS) -c hello_sidharth.c

main:hello
	$(CC) $(CFLAGS) hello_sidharth.o main_sidharth.c -o main_sidharth

run:
	./main_sidharth

clean:
	rm main_sidharth